services:
  app:
    build: .
    ports:
      - 3000:3000
    networks:
      - lan-net
    environment:
      FLASK_API_URL: # api backend
      JWT_SECRET: # super secret

networks:
  lan-net:
    external: true
